
import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;

/**
 *
 * @author Jamie
 */
public class Netstater extends javax.swing.JFrame {
    /**
     * Creates new form Netstater
     */
    
    // Having the string array for the tags is actually a genuis solution
    // Only thing i hate is that they are global variables but I kinda need it to be that way
    
    public static String command = "netstat";
    public static String tags[] = {"", "", "", "", ""};
    
    public Netstater() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipv4_Toggle2 = new javax.swing.JToggleButton();
        ipv6_Toggle2 = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        run_Button = new javax.swing.JButton();
        tab_Menu = new javax.swing.JTabbedPane();
        options_Panel = new javax.swing.JPanel();
        stats_Toggle = new javax.swing.JToggleButton();
        ethernet_Toggle = new javax.swing.JToggleButton();
        routing_Toggle = new javax.swing.JToggleButton();
        tcp_Button = new javax.swing.JButton();
        udp_Button = new javax.swing.JButton();
        ipv6_Button = new javax.swing.JButton();
        ipv4_Button = new javax.swing.JButton();
        icmp_Button = new javax.swing.JButton();
        log_Panel = new javax.swing.JPanel();
        logging_Toggle = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        themes_Panel = new javax.swing.JPanel();
        plain_Theme_Button = new javax.swing.JButton();
        dark_Theme_Button = new javax.swing.JButton();
        contrast_Theme_Button = new javax.swing.JButton();
        flux_Theme_Button = new javax.swing.JButton();
        help_Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        help_Text_Area = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_Area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        ipv4_Toggle2.setText("IPV4");
        ipv4_Toggle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipv4_Toggle2ActionPerformed(evt);
            }
        });

        ipv6_Toggle2.setText("IPV6");

        jButton5.setText("jButton5");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 550));
        setPreferredSize(new java.awt.Dimension(600, 550));

        run_Button.setText("Run");
        run_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_ButtonActionPerformed(evt);
            }
        });

        stats_Toggle.setText("Statistics");
        stats_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stats_ToggleActionPerformed(evt);
            }
        });

        ethernet_Toggle.setText("Ethernet");
        ethernet_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ethernet_ToggleActionPerformed(evt);
            }
        });

        routing_Toggle.setText("Routing Table");
        routing_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routing_ToggleActionPerformed(evt);
            }
        });

        tcp_Button.setText("TCP");
        tcp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcp_ButtonActionPerformed(evt);
            }
        });

        udp_Button.setText("UDP");
        udp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udp_ButtonActionPerformed(evt);
            }
        });

        ipv6_Button.setText("IPV6");
        ipv6_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipv6_ButtonActionPerformed(evt);
            }
        });

        ipv4_Button.setText("IPV4");
        ipv4_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipv4_ButtonActionPerformed(evt);
            }
        });

        icmp_Button.setText("ICMP");
        icmp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icmp_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout options_PanelLayout = new javax.swing.GroupLayout(options_Panel);
        options_Panel.setLayout(options_PanelLayout);
        options_PanelLayout.setHorizontalGroup(
            options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(options_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipv6_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ipv4_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcp_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(udp_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icmp_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stats_Toggle, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ethernet_Toggle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(routing_Toggle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap())
        );
        options_PanelLayout.setVerticalGroup(
            options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, options_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(options_PanelLayout.createSequentialGroup()
                        .addComponent(routing_Toggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stats_Toggle)
                            .addComponent(ethernet_Toggle)))
                    .addGroup(options_PanelLayout.createSequentialGroup()
                        .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcp_Button)
                            .addComponent(ipv4_Button)
                            .addComponent(icmp_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(udp_Button)
                            .addComponent(ipv6_Button))))
                .addContainerGap())
        );

        tab_Menu.addTab("Options", options_Panel);

        logging_Toggle.setText("Logging");
        logging_Toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logging_ToggleActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("If Selected A New Folder Will Be Made Named Log Where The Output Will Be Stored");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout log_PanelLayout = new javax.swing.GroupLayout(log_Panel);
        log_Panel.setLayout(log_PanelLayout);
        log_PanelLayout.setHorizontalGroup(
            log_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(log_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logging_Toggle, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, log_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        log_PanelLayout.setVerticalGroup(
            log_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_PanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logging_Toggle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_Menu.addTab("Logging", log_Panel);

        plain_Theme_Button.setText("Plain");
        plain_Theme_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plain_Theme_ButtonActionPerformed(evt);
            }
        });

        dark_Theme_Button.setText("Dark");
        dark_Theme_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dark_Theme_ButtonActionPerformed(evt);
            }
        });

        contrast_Theme_Button.setText("High Contrast");
        contrast_Theme_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrast_Theme_ButtonActionPerformed(evt);
            }
        });

        flux_Theme_Button.setText("Late Night");
        flux_Theme_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flux_Theme_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout themes_PanelLayout = new javax.swing.GroupLayout(themes_Panel);
        themes_Panel.setLayout(themes_PanelLayout);
        themes_PanelLayout.setHorizontalGroup(
            themes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themes_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(themes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contrast_Theme_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(plain_Theme_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(themes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dark_Theme_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(flux_Theme_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        themes_PanelLayout.setVerticalGroup(
            themes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(themes_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(themes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dark_Theme_Button)
                    .addComponent(plain_Theme_Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(themes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flux_Theme_Button)
                    .addComponent(contrast_Theme_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_Menu.addTab("Themes", themes_Panel);

        help_Text_Area.setEditable(false);
        help_Text_Area.setColumns(20);
        help_Text_Area.setRows(5);
        help_Text_Area.setText("IPv4, IPv6, TCP, UDP and ICMP can't be used in conjuction.\nStatistics, Routing Table and Ethernet can be used togther.\nAll log data will be added to the Log Folder.\nFeel free to contact us; netstarter@llf.com");
        jScrollPane2.setViewportView(help_Text_Area);

        javax.swing.GroupLayout help_PanelLayout = new javax.swing.GroupLayout(help_Panel);
        help_Panel.setLayout(help_PanelLayout);
        help_PanelLayout.setHorizontalGroup(
            help_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(help_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(help_PanelLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane2)
                    .addGap(10, 10, 10)))
        );
        help_PanelLayout.setVerticalGroup(
            help_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
            .addGroup(help_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
        );

        tab_Menu.addTab("Help", help_Panel);

        text_Area.setEditable(false);
        text_Area.setColumns(20);
        text_Area.setRows(5);
        jScrollPane1.setViewportView(text_Area);

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel2.setText("NetStater");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_Menu)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(run_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tab_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(run_Button)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stats_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stats_ToggleActionPerformed
        // TODO add your handling code here:
        if (stats_Toggle.isSelected())
            tags[1] = " -s";
        else  
            tags[1] = "";  
    }//GEN-LAST:event_stats_ToggleActionPerformed

    private void ipv4_Toggle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipv4_Toggle2ActionPerformed

    }//GEN-LAST:event_ipv4_Toggle2ActionPerformed

    private void routing_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routing_ToggleActionPerformed
        // TODO add your handling code here:
        if (routing_Toggle.isSelected())
            tags[2] = " -r";
        else  
            tags[2] = ""; 
    }//GEN-LAST:event_routing_ToggleActionPerformed

    private void tcp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcp_ButtonActionPerformed
        // TODO add your handling code here:
        tags[0] = " -p tcp";
    }//GEN-LAST:event_tcp_ButtonActionPerformed

    private void ipv4_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipv4_ButtonActionPerformed
        // TODO add your handling code here:
        
        tags[0] = " -p ip";
 
    }//GEN-LAST:event_ipv4_ButtonActionPerformed

    private void flux_Theme_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flux_Theme_ButtonActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(new java.awt.Color(255,165,76));
        text_Area.setBackground(new java.awt.Color(255,216,178));
        help_Text_Area.setBackground(new java.awt.Color(255,216,178));
        setButtons(new java.awt.Color(255,235,210));
        setTabs(new java.awt.Color(255,165,76));
    }//GEN-LAST:event_flux_Theme_ButtonActionPerformed

    private void ipv6_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipv6_ButtonActionPerformed
        // TODO add your handling code here:
        
        tags[0] = " -p ipv6";
    }//GEN-LAST:event_ipv6_ButtonActionPerformed

    private void udp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udp_ButtonActionPerformed
        // TODO add your handling code here:
        tags[0] = " -p udp";
    }//GEN-LAST:event_udp_ButtonActionPerformed

    private void icmp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icmp_ButtonActionPerformed
        // TODO add your handling code here:
        tags[0] = " -p icmp";
    }//GEN-LAST:event_icmp_ButtonActionPerformed

    private void run_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_ButtonActionPerformed
        // TODO add your handling code here:
        /* IF THERE IS AN ISSUE MAKE SURE THERE IS A SPACE " " BETWEEN EACH TAG */
        
        // Windows cmd output to a file isnt working correctly
        String exe = command + tags[0] + tags[1] + tags[2] + tags[3];
        System.out.println(exe);
 
        try {
            Process process = Runtime.getRuntime().exec(exe);

            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                String output = "";
                while ((line = reader.readLine()) != null) {
                    output += (line + "\r\n");
  
                }
                text_Area.setFont( new Font("monospaced", Font.PLAIN, 12) );
                text_Area.setText(output);
            }

        } catch (IOException e) {
        }
    }//GEN-LAST:event_run_ButtonActionPerformed

    private void ethernet_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ethernet_ToggleActionPerformed
        // TODO add your handling code here:
        if (ethernet_Toggle.isSelected())
            tags[3] = " -e";
        else  
            tags[3] = ""; 
    }//GEN-LAST:event_ethernet_ToggleActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void plain_Theme_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plain_Theme_ButtonActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(new java.awt.Color(211, 211, 211));
        text_Area.setBackground(new java.awt.Color(255, 255, 255));
        help_Text_Area.setBackground(new java.awt.Color(255, 255, 255));
        setButtons(new java.awt.Color(211, 211, 211));
        setTabs(new java.awt.Color(211, 211, 211));
    }//GEN-LAST:event_plain_Theme_ButtonActionPerformed

    private void dark_Theme_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dark_Theme_ButtonActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        text_Area.setBackground(java.awt.Color.GRAY);
        help_Text_Area.setBackground(java.awt.Color.GRAY);
        setButtons(java.awt.Color.GRAY);
        setTabs(java.awt.Color.DARK_GRAY);
    }//GEN-LAST:event_dark_Theme_ButtonActionPerformed

    private void contrast_Theme_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrast_Theme_ButtonActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(java.awt.Color.BLACK);
        text_Area.setBackground(java.awt.Color.WHITE);
        help_Text_Area.setBackground(java.awt.Color.WHITE);
        setButtons(java.awt.Color.WHITE);
        setTabs(java.awt.Color.BLACK);
    }//GEN-LAST:event_contrast_Theme_ButtonActionPerformed

    private void logging_ToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logging_ToggleActionPerformed
        // TODO add your handling code here:
        String date = null;
        if (logging_Toggle.isSelected())
        {
            new File("./Logging").mkdir();
            date = getDateTime();
            tags[4] = (" > .\\Logging\\" + date + ".txt");
        }
        else  
            tags[4] = ""; 
        
        
    }//GEN-LAST:event_logging_ToggleActionPerformed

    private  final static String getDateTime()  
    {  
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd_hh:mm:ss");  
        df.setTimeZone(TimeZone.getTimeZone("GMT+8"));  
        return df.format(new Date());  
    }
    public void setTabs(java.awt.Color inColor)
    {
        tab_Menu.setBackground(inColor);
        options_Panel.setBackground(inColor);
        log_Panel.setBackground(inColor);
        themes_Panel.setBackground(inColor);
        help_Panel.setBackground(inColor);
    }
    public void setButtons(java.awt.Color inColor) {
        ipv4_Button.setBackground(inColor);
        ipv6_Button.setBackground(inColor);
        tcp_Button.setBackground(inColor);
        udp_Button.setBackground(inColor);
        icmp_Button.setBackground(inColor);
        stats_Toggle.setBackground(inColor);
        routing_Toggle.setBackground(inColor);
        ethernet_Toggle.setBackground(inColor);
        logging_Toggle.setBackground(inColor);
        plain_Theme_Button.setBackground(inColor);
        dark_Theme_Button.setBackground(inColor);
        contrast_Theme_Button.setBackground(inColor);
        flux_Theme_Button.setBackground(inColor);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Netstater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Netstater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Netstater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Netstater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Netstater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contrast_Theme_Button;
    private javax.swing.JButton dark_Theme_Button;
    private javax.swing.JToggleButton ethernet_Toggle;
    private javax.swing.JButton flux_Theme_Button;
    private javax.swing.JPanel help_Panel;
    private javax.swing.JTextArea help_Text_Area;
    private javax.swing.JButton icmp_Button;
    private javax.swing.JButton ipv4_Button;
    private javax.swing.JToggleButton ipv4_Toggle2;
    private javax.swing.JButton ipv6_Button;
    private javax.swing.JToggleButton ipv6_Toggle2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel log_Panel;
    private javax.swing.JToggleButton logging_Toggle;
    private javax.swing.JPanel options_Panel;
    private javax.swing.JButton plain_Theme_Button;
    private javax.swing.JToggleButton routing_Toggle;
    private javax.swing.JButton run_Button;
    private javax.swing.JToggleButton stats_Toggle;
    private javax.swing.JTabbedPane tab_Menu;
    private javax.swing.JButton tcp_Button;
    private javax.swing.JTextArea text_Area;
    private javax.swing.JPanel themes_Panel;
    private javax.swing.JButton udp_Button;
    // End of variables declaration//GEN-END:variables
}
